### ISSUE TITLE
Uncaught TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by vasa-chi** [mehcode/atom-project-plus#14]
[Enter steps to reproduce below:]
1. Ctrl-Cmd-P
2. Input something into search input
3. Remove everything in the search input

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [project-plus](https://github.com/mehcode/atom-project-plus) package, v0.4.3
### Stack Trace

Uncaught TypeError: Cannot read property 'replace' of undefined

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:319

TypeError: Cannot read property 'replace' of undefined
    at Builder.text (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:319:29)
    at Function.View.text (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:92:34)
    at Object.content (/Users/vasa/.atom/packages/project-plus/lib/project-finder-view.coffee:61:12)
    at Builder.tag (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:281:19)
    at Function.View.(anonymous function) [as div] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:83:49)
    at Object.content (/Users/vasa/.atom/packages/project-plus/lib/project-finder-view.coffee:60:10)
    at Builder.tag (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:281:19)
    at Function.View.(anonymous function) [as li] (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:83:49)
    at Function.<anonymous> (/Users/vasa/.atom/packages/project-plus/lib/project-finder-view.coffee:56:8)
    at Function.View.buildHtml (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:123:10)
    at Function.View.render (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:129:19)
    at exports.$$ (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:627:24)
    at ProjectPlusView.module.exports.ProjectPlusView.viewForItem (/Users/vasa/.atom/packages/project-plus/lib/project-finder-view.coffee:55:5)
    at ProjectPlusView.module.exports.SelectListView.populateList (/Users/vasa/.atom/packages/project-plus/node_modules/atom-space-pen-views/lib/select-list-view.js:206:29)
    at /Users/vasa/.atom/packages/project-plus/node_modules/atom-space-pen-views/lib/select-list-view.js:350:26
```
### Commands

```
     -0:07.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:05.3.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:05.3.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:04.5.0 project-plus:toggle-project-finder (atom-text-editor.editor.is-focused)
     -0:02.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:02.0 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.js.jsx": [
        "js",
        "jsx",
        "es6"
      ]
    },
    "disabledPackages": [
      "atom-ctags",
      "linter-scss-lint",
      "autosave",
      "autocomplete",
      "linter-python-pyflakes",
      "project-manager"
    ],
    "packagesWithKeymapsDisabled": [
      "color-picker",
      "highlight-line"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.4
atom-django, v0.3.2
atom-material-syntax, v0.4.3
atom-material-ui, v1.2.0
autoclose-html, v0.23.0
autocomplete-modules, v1.4.1
autocomplete-paths, v1.0.2
autocomplete-python, v1.7.0
block-travel, v1.0.4
color-picker, v2.1.1
compare-files, v0.6.2
django-templates, v0.5.0
editorconfig, v1.2.4
emmet, v2.4.1
file-icons, v1.6.17
git-diff-details, v0.23.0
git-log, v0.4.1
highlight-line, v0.11.1
highlight-selected, v0.11.2
language-babel, v2.15.4
language-elixir, v0.11.1
language-elm, v1.3.3
linter, v1.11.3
linter-eslint, v7.0.0
linter-flake8, v1.12.1
linter-jsonlint, v1.1.6
linter-less, v2.4.2
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-pigments, v0.1.7
pigments, v0.24.2
project-plus, v0.4.3
python-isort, v0.0.7

# Dev
No dev packages
```

**Comment by mehcode** [comment]
Wow.. I would love to see your editor state. Hmm. 

The error is saying that you have a project state such that it's path array is `[null]`. That seems like some package you've used in the past corrupted the state. I've adjusted the package to make extra sure we don't look at state that is corrupted like that.

Thank you for working through this and let me know if you have another problem.

**Comment by vasa-chi** [comment]
I use https://atom.io/packages/project-manager for now, so maybe it causes the state error? Still, I disable it when I try your plugin :)

**Comment by mehcode** [comment]
Heh. No idea. A collegue got the same error as well and I don't think he used it either. Although he had several dozen packages installed so it could be anything. 

Anyway.. did this fix it for you?

**Comment by vasa-chi** [comment]
Hmm, no, still getting it.

**Comment by mehcode** [comment]
Ah. I forgot a case. Should have a fix pushed soon.

**Comment by mehcode** [comment]
@vasa-chi Can you give 0.5.0 a try?

**Comment by vasa-chi** [comment]
Yep, works fine now. Thanks!

**Comment by mehcode** [comment]
:clap:
