### ISSUE TITLE
Uncaught TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by benw01** [mehcode/atom-project-plus#22]
[Enter steps to reproduce below:]
1. start atom
2. press ctrl+alt+p

**Atom Version**: 1.5.4
**System**: Ubuntu 15.10
**Thrown From**: [project-plus](https://github.com/mehcode/atom-project-plus) package, v0.7.0
### Stack Trace

Uncaught TypeError: Cannot read property 'map' of undefined

```
At /home/iisbwil/.atom/packages/project-plus/lib/util.coffee:70

TypeError: Cannot read property 'map' of undefined
    at /home/iisbwil/.atom/packages/project-plus/lib/util.coffee:70:30
    at Array.map (native)
    at filterProjects (/home/iisbwil/.atom/packages/project-plus/lib/util.coffee:68:15)
    at /home/iisbwil/.atom/packages/project-plus/lib/util.coffee:166:19
    at /home/iisbwil/.atom/packages/project-plus/node_modules/async/lib/async.js:52:16
    at /home/iisbwil/.atom/packages/project-plus/node_modules/async/lib/async.js:361:13
    at /home/iisbwil/.atom/packages/project-plus/node_modules/async/lib/async.js:52:16
    at done (/home/iisbwil/.atom/packages/project-plus/node_modules/async/lib/async.js:246:17)
    at /home/iisbwil/.atom/packages/project-plus/node_modules/async/lib/async.js:44:16
    at /home/iisbwil/.atom/packages/project-plus/node_modules/async/lib/async.js:358:17
    at /home/iisbwil/.atom/packages/project-plus/lib/util.coffee:162:15
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
```
### Commands

```
     -0:35 application:add-project-folder (atom-text-editor.editor.is-focused)
     -0:03.5.0 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -0:02.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -0:02.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -0:00.9.0 project-plus:toggle-project-finder (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "spell-check"
    ],
    "ignoredNames": [
      ".git",
      ".hg",
      ".svn",
      ".DS_Store",
      "Thumbs.db",
      "*~"
    ],
    "themes": [
      "atom-light-ui",
      "solarized-dark-syntax"
    ]
  },
  "project-plus": {}
}
```
### Installed Packages

``` coffee
# User
git-diff-details, v0.23.0
html-entities, v0.4.0
language-apache, v1.4.0
language-dot, v1.6.0
language-generic-config, v1.0.0
language-puppet, v0.17.0
language-txtasmarkdown, v0.1.0
linter, v1.11.3
linter-erb, v1.0.2
linter-puppet, v1.0.0
markdown-table-formatter, v2.8.0
minimap, v4.20.0
minimap-git-diff, v4.2.0
project-plus, v0.7.0
recent-projects, v0.9.5
tree-view-open-files, v0.3.0

# Dev
No dev packages
```

**Comment by mehcode** [comment]
Thanks for reporting this @benw01; let me know if there are any other issues.
