### ISSUE TITLE
Doesn't save projects.

### ISSUE THREAD

**Issue by trusktr** [mehcode/atom-project-plus#51]
Not sure how it works, but I set the "Project Home" setting to `~/.atom/session`, and then I run the `Project Plus: Save` command, which shows the green success notification, but when I press cmd-ctrl-p to see projects, the list is empty.

**Comment by trusktr** [comment]
If I remove the setting, it works. Where is it saving the projects by default?  The UI doesn't show the default value:

![screen shot 2016-06-12 at 3 04 51 am](https://cloud.githubusercontent.com/assets/297678/15990547/74c29918-304a-11e6-83e4-0e80cffc5a5d.png)

**Comment by mehcode** [comment]
@trusktr Hmm.. Perhaps the setting is badly worded. It's older and `Project Plus: Save` was added much later.

`Project Home` is strictly a filter for the project finder. Normal/default operation of project-plus uses auto-discovery and the setting is intended to reign in the auto-discovery to a single folder (and all its children).

Projects saved via `Project Plus: Save` are found in `~/.atom/projects.cson` -- there should be a command `Project Plus: Edit Projects` to open that file. That save command is intended for use if auto-discovery is disabled.

**Comment by trusktr** [comment]
For sure. So with the default `Project Home` option, where does the state get saved (open tabs, panes, cursor location, etc)?

**Comment by nanohard** [comment]
~~I'm having this issue as well. Could you upload an example `projects.cson`? That would solve my problem.~~

Okay, so I didn't know what the Command Palette was, so what?

**Comment by mehcode** [comment]
> For sure. So with the default Project Home option, where does the state get saved (open tabs, panes, cursor location, etc)?

@trusktr This package actually doesn't save your state. Atom does. You can find it by opening up developer tools, and going to resources. It's under IndexedDB.

---

@nanohard Did you figure out what you were trying to figure out?

**Comment by nanohard** [comment]
@mehcode Yeah, I thought the command palette was the same as what pops up when you press the keyboard shortcut for this plugin. Works great for me. Thanks for this.

**Comment by nomoth** [comment]
I have the same issue but even with Project Home unset.
When I save the project, I got the green notification but the projects.cson file is not modified.
As a workaround I used project-manager to save the project.

**Comment by pt8o** [comment]
Same issue. I'm running project-plus completely vanilla. When I save I get the green checkmark, but when I go looking for them it says that no projects are saved.

**Comment by willdawsonme** [comment]
@nomoth @suprko Any console errors in Atom's inspector (`View > Developer > Toggle Developer Tools`)?

**Comment by nomoth** [comment]
@willdawsonme one error for me but not sure it concerns project-plus:

```
helpers.js:92 [Package-Deps] Unable to get loaded package 'usr'
getDependencies @ helpers.js:92
```

**Comment by willdawsonme** [comment]
@nomoth Yeah unlikely to be from this package! Just to clarify, no matter what project you try to save, you get the green success notification but `~/.atom/projects.cson` isn't updated and you don't see the new project in the list within atom?

A few things to check:
- What OS are using?
- What version of atom?
- Are there any pending updates for project plus?

Also, just to rule out another conclusion, could you rename `projects.cson` to `projects.cson.backup` and try saving again? A new file should be created with the saved project.

**Comment by erbridge** [comment]
Running `Project Plus: Save` had no effect for me, too, but deleting the `projects.cson` and trying again fixed the issue. Possibly an issue updating the default file?

**Comment by poomv2** [comment]
Hi there, when you saying run `Project Plus: Save`, is that the actual command? If so, where do I run this?

Thanks Steve

**Comment by gtozzi** [comment]
Hi, I also can't save projects anymore. I get this:

```
Uncaught (in promise) TypeError: _atomProjectUtil2.default.save is not a function
    at SessionProvider.save (~/.atom/packages/project-plus/lib/provider/session.js:131:28)
    at ~/.atom/packages/project-plus/lib/provider-manager.js:33:26
    at Array.map (native)
    at ~/.atom/packages/project-plus/lib/provider-manager.js:32:39
    at ProviderManager.invoke (~/.atom/packages/project-plus/lib/provider-manager.js:31:12)
    at ProviderManager.save (~/.atom/packages/project-plus/lib/provider-manager.js:63:17)
    at atom-workspace.projectPlusSave (~/.atom/packages/project-plus/lib/project-plus.js:40:25)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom/resources/app/src/command-registry.js:3:65
    at Object.didConfirmSelection (/usr/share/atom/resources/app/node_modules/command-palette/lib/command-palette-view.js:106:35)
    at SelectListView.confirmSelection (/usr/share/atom/resources/app/node_modules/atom-select-list/src/select-list-view.js:313:26)
    at HTMLDivElement.core:confirm (/usr/share/atom/resources/app/node_modules/atom-select-list/src/select-list-view.js:81:20)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/src/command-registry.js:265:35)
    at /usr/share/atom/resources/app/src/command-registry.js:3:65
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:610:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/node_modules/atom-keymap/lib/keymap-manager.js:401:28)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/src/window-event-handler.js:100:42)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:3:65)
```

**Comment by billdami** [comment]
@gtozzi I'm getting the same exact error as you. Running latest version of project-plus and atom@v.18.0 x64 (macOS Sierra)

**Comment by kevinisaac** [comment]
Project save doesn't save the project at all. I have a list of 6 projects showing when trying to find the projects but that's it. New projects aren't being saved.
