### ISSUE TITLE
Switching projects fails in Atom 1.17.0

### ISSUE THREAD

**Issue by McSodbrenner** [mehcode/atom-project-plus#96]
In the Developer tools the following error appears:

```
C:\Users\...\.atom\packages\project-plus\node_modules\atom-project-util\index.js:87 Uncaught (in promise) Error: The workspace can only contain one instance of item [object Object]
    at ItemRegistry.module.exports.ItemRegistry.addItem (C:\Users\...\AppData\Local\atom\app-1.17.0\resources\app\src\item-registry.js:11:1)
    at PaneContainer.didAddPaneItem (C:\Users\...\AppData\Local\atom\app-1.17.0\resources\app\src\pane-container.js:265:1)
    at PaneContainer.didAddPane (C:\Users\...\AppData\Local\atom\app-1.17.0\resources\app\src\pane-container.js:238:1)
    at Pane.module.exports.Pane.setContainer (C:\Users\...\AppData\Local\atom\app-1.17.0\resources\app\src\pane.js:149:1)
    at PaneContainer.setRoot (C:\Users\...\AppData\Local\atom\app-1.17.0\resources\app\src\pane-container.js:134:1)
    at PaneContainer.deserialize (C:\Users\...\AppData\Local\atom\app-1.17.0\resources\app\src\pane-container.js:55:1)
    at Dock.deserialize (C:\Users\...\AppData\Local\atom\app-1.17.0\resources\app\src\dock.js:373:1)
    at Workspace.deserialize (C:\Users\...\AppData\Local\atom\app-1.17.0\resources\app\src\workspace.js:415:1)
    at AtomEnvironment.module.exports.AtomEnvironment.deserialize (C:\Users\...\AppData\Local\atom\app-1.17.0\resources\app\src\atom-environment.js:1213:1)
    at atomDeserialize (C:\Users\...\.atom\packages\project-plus\node_modules\atom-project-util\index.js:87:45)
    at loadState.then (C:\Users\...\.atom\packages\project-plus\node_modules\atom-project-util\index.js:152:11)
```

**Comment by mehcode** [comment]
Fixed and released as v1.0
